import os
import uuid
import re
import random
import edge_tts
from typing import Optional

def clean_text(text: str) -> str:
    """Removes overly formal or robotic phrases generated by the LLM."""
    robotic_phrases = [
        "I understand that",
        "It appears that",
        "Based on your input",
        "As an AI",
        "I am an artificial intelligence"
    ]
    for phrase in robotic_phrases:
        # Case insensitive replacement
        text = re.compile(re.escape(phrase), re.IGNORECASE).sub("", text)
    
    return text.strip()

def humanize_text(text: str, emotion: Optional[str] = None) -> str:
    """
    Randomly injects human fillers, adds natural pauses, and modifies
    phrasing based on emotional context.
    """
    text = clean_text(text)
    if not text:
        return ""
        
    ltext = text.lower()
    
    # 1. Add natural starters (~40% chance)
    fillers = ["Yeah... ", "Hmm... ", "Okay... ", "I get that... "]
    if random.random() < 0.40 and not any(ltext.startswith(f.lower().strip('. ')) for f in fillers):
        selected_filler = random.choice(fillers)
        text = selected_filler + text
        
    # 2. Insert natural pauses (replace ". " with "... ")
    text = text.replace(". ", "... ")
    
    # 3. Apply emotional tone adjustments
    if emotion in ["stressed", "sad", "fatigue"]:
        # Replace stiff phrasing with softer language
        text = text.replace("You should", "Maybe try to")
        text = text.replace("You need to", "It might help to")
        text = text.replace("You have to", "I think you could")
        # Ensure we always have a gentle filler for stressed scenarios if not randomly picked
        if not text.startswith("Yeah") and not text.startswith("Hmm") and not text.startswith("Okay") and not text.startswith("I get that"):
             text = "Hmm... " + text
             
    elif emotion in ["happy", "positive"]:
        # Make the response slightly more energetic by removing some heavy pacing
        text = text.replace("... ", ", ")
        
    # Capitalize first letter cleanly
    text_len = len(text)
    return text[0].upper() + text[1:text_len] if text else ""

def prepare_text(text: str) -> str:
    """
    Cleans structural text to manipulate the Neural TTS generation.
    It ensures natural respiration pauses via punctuation mapping.
    """
    text = text.strip()
    if not text:
        return ""
        
    # Convert arbitrary excessive ellipses into standard resting gaps
    text = re.sub(r'\.{4,}', '...', text)
    
    # The neural matrix needs termination characters to correctly pitch the end of a sentence
    if not text.endswith((".", "?", "!")):
        text += "."
        
    return text

async def text_to_speech(text: str, emotion: Optional[str] = None) -> Optional[str]:
    """
    Synthesizes and saves AI voice locally via the Microsoft Edge API (JennyNeural).
    Runs completely asynchronously inside FastAPI to prevent thread blocking.
    """
    
    # Apply deep text humanization and robotic phrase stripping
    text = humanize_text(text, emotion)
    
    processed_text = prepare_text(text)
    if not processed_text:
        return ""
        
    # Default parameters based on user rules
    voice = "en-US-JennyNeural"
    rate = "+10%"
    pitch = "-2Hz"
    
    # Subtle emotion-based voice mapping (altering the rate mostly)
    if emotion in ["stressed", "sad", "fatigue", "angry"]:
        rate = "+0%"  # Slow it down slightly from the default fast pace baseline
        pitch = "-4Hz" # Lower, calmer pitch
    elif emotion in ["happy", "positive"]:
        rate = "+15%"  # slightly higher tempo
        pitch = "+0Hz" # standard pitch
        
    # Generate unique caching filename
    filename = f"response_{uuid.uuid4().hex[:8]}.mp3"
    audio_dir = os.path.join(os.getcwd(), "audio")
    os.makedirs(audio_dir, exist_ok=True)
    
    file_path = os.path.join(audio_dir, filename)
    
    # Send text out to Edge inference engine with highly controlled pacing modifiers
    communicate = edge_tts.Communicate(
        text=processed_text, 
        voice=voice,
        rate=rate,
        pitch=pitch
    )
    
    try:
        await communicate.save(file_path)
        return f"/audio/{filename}"
    except Exception as e:
        print(f"TTS Engine Error (Network/DNS): {e}")
        return None
